In [1]:
import pandas as pd, matplotlib.pyplot as plt, numpy as np, os, datetime as dt

In C:\Users\Kyle\anaconda3\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle:
The text.latex.preview rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
In C:\Users\Kyle\anaconda3\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle:
The mathtext.fallback_to_cm rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
In C:\Users\Kyle\anaconda3\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle: Support for setting the 'mathtext.fallback_to_cm' rcParam is deprecated since 3.3 and will be removed two minor releases later; use 'mathtext.fallback : 'cm' instead.
In C:\Users\Kyle\anaconda3\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle:
The validate_bool_maybe_none function was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
In C:\Users\Kyle\anaconda3\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle:
The savefig.jpeg_quality rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
In C:\Users\Kyle\anaconda3\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle:
The keymap.all_axes rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
In C:\Users\Kyle\anaconda3\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle:
The animation.avconv_path rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
In C:\Users\Kyle\anaconda3\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle:
The animation.avconv_args rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.

In [2]:
df = pd.read_csv("../data/interim/results_Season_2021.txt", names=["Day", "Mo_day", "Year", "Time", "Opponent", "Result", "Score_team", "Score_opp", "Ws", "Ls","Streak", "Home","OT", "teamcode", "gamecode", "Location_spc"])

In [3]:
df.head()

,Day,Mo_day,Year,Time,Opponent,Result,Score_team,Score_opp,Ws,Ls,Streak,Home,OT,teamcode,gamecode,Location_spc
0,Wed,Dec 23,2020,7:30p,New Orleans Pelicans,L,99,113,0,1,L 1,HOME,NaN,TOR,202012230TOR,NaN
1,Sat,Dec 26,2020,8:30p,San Antonio Spurs,L,114,119,0,2,L 2,AWAY,NaN,TOR,NaN,NaN
2,Tue,Dec 29,2020,7:00p,Philadelphia 76ers,L,93,100,0,3,L 3,AWAY,NaN,TOR,NaN,NaN
3,Thu,Dec 31,2020,7:30p,New York Knicks,W,100,83,1,3,W 1,HOME,NaN,TOR,202012310TOR,NaN
4,Sat,Jan 2,2021,7:30p,New Orleans Pelicans,L,116,120,1,4,L 1,AWAY,NaN,TOR,NaN,NaN

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2342 entries, 0 to 2341
Data columns (total 16 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Day           2342 non-null   object
 1   Mo_day        2342 non-null   object
 2   Year          2342 non-null   int64
 3   Time          2342 non-null   object
 4   Opponent      2342 non-null   object
 5   Result        2342 non-null   object
 6   Score_team    2342 non-null   int64
 7   Score_opp     2342 non-null   int64
 8   Ws            2342 non-null   int64
 9   Ls            2342 non-null   int64
 10  Streak        2342 non-null   object
 11  Home          2342 non-null   object
 12  OT            120 non-null    object
 13  teamcode      2342 non-null   object
 14  gamecode      1171 non-null   object
 15  Location_spc  0 non-null      float64
dtypes: float64(1), int64(5), object(10)
memory usage: 292.9+ KB

In [5]:
# post ALL-Star Break
df_post_all_star = df[df["Year"] > 2020]

In [6]:
df_post_all_star

,Day,Mo_day,Year,Time,Opponent,Result,Score_team,Score_opp,Ws,Ls,Streak,Home,OT,teamcode,gamecode,Location_spc
4,Sat,Jan 2,2021,7:30p,New Orleans Pelicans,L,116,120,1,4,L 1,AWAY,NaN,TOR,NaN,NaN
5,Mon,Jan 4,2021,7:30p,Boston Celtics,L,114,126,1,5,L 2,HOME,NaN,TOR,202101040TOR,NaN
6,Wed,Jan 6,2021,9:00p,Phoenix Suns,L,115,123,1,6,L 3,AWAY,NaN,TOR,NaN,NaN
7,Fri,Jan 8,2021,10:00p,Sacramento Kings,W,144,123,2,6,W 1,AWAY,NaN,TOR,NaN,NaN
8,Sun,Jan 10,2021,8:30p,Golden State Warriors,L,105,106,2,7,L 1,AWAY,NaN,TOR,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2337,Wed,May 12,2021,8:00p,Brooklyn Nets,L,116,128,33,36,L 1,AWAY,NaN,SAS,NaN,NaN
2338,Thu,May 13,2021,7:30p,New York Knicks,L,98,102,33,37,L 2,AWAY,NaN,SAS,NaN,NaN
2339,Sat,May 15,2021,2:00p,Phoenix Suns,L,103,140,33,38,L 3,HOME,NaN,SAS,202105150SAS,NaN
2340,Sun,May 16,2021,2:00p,Phoenix Suns,L,121,123,33,39,L 4,HOME,NaN,SAS,202105160SAS,NaN
2341,Wed,May 19,2021,7:30p,Memphis Grizzlies,L,96,100,33,40,L 5,AWAY,NaN,SAS,NaN,NaN

In [7]:
df_post_all_star.Year = df_post_all_star.Year.astype(str)

C:\Users\Kyle\anaconda3\lib\site-packages\pandas\core\generic.py:5165: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value

In [8]:
df_post_all_star["DT"] = df_post_all_star["Mo_day"] + " " + df_post_all_star["Year"]

C:\Users\Kyle\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [9]:
df_post_all_star.DT = pd.to_datetime(df_post_all_star.DT, format=" %b %d %Y")

In [10]:
df_final = df_post_all_star[df_post_all_star.DT > dt.datetime(2021, 3, 4)]

In [11]:
df_final = df_final.iloc[:, :-1]

In [12]:
df_final = df_final.fillna(value="null")

In [13]:
df_final.to_csv("../data/interim/results_Season_2021_postallstar.txt", index=False, header=False)